### ISSUE TITLE
broadcast hex: bad-txs-and-input-times

### ISSUE THREAD

**Issue by HebeBlock** [vergecurrency/bitcore#10]
HI, I am using: https://github.com/vergecurrency/bitcore/tree/master/packages/bitcore-lib
Error after signing broadcast hex: bad-txs-and-input-times, input-time (1589536675)> tx-time (0) (code 16)
How can someone fix it?

hex:010000000000000001bceac0f783a7f48a8339b331c8bf5904dbf3804edf0617fca5c5420dde2616ed000000006b483045022100a406e9317b1606c83b5d37dc48a06c94b3e7221c9bb6b31001bf3c34259f091402200639e969924657c8a2bde3054b9304e891b05c96adffedf3b537c71d83c10c29012103fdf4907810a9f5d9462a1ae09feee5ab205d32798b0ffcc379442021f84c5bbfffffffff0200e1f505000000001976a914e6e8b8e5f5683bc0e2203e89346fde8587d5593e88ac80df1710000000001976a9148d4d508f5bf2c28b20a3863405f05d3cd374b04588ac00000000

**Comment by justinvforvendetta** [comment]
@HebeBlock sounds like your computers clock might be off? your verge daemon is running properly?

**Comment by HebeBlock** [comment]
@justinvforvendetta I'm using a third-party API. I guess it's their problem. Can you provide me an API that can send hex?

**Comment by justinvforvendetta** [comment]
what api did you try?

**Comment by HebeBlock** [comment]
@justinvforvendetta https://xvgapi.guarda.co/api/XVG/mainnet/tx/send

**Comment by HebeBlock** [comment]
https://api.vergecurrency.network/node/api/XVG/mainnet/tx/send , Same error

**Comment by justinvforvendetta** [comment]
what part looks wrong when you decode the tx?

**Comment by HebeBlock** [comment]
`{"hash":"2263e7bac79c83e3ddf94c9b7d271e43d2dbf5834db70facf28e2284f190c469","version":1,"inputs":[{"prevTxId":"ed1626de0d42c5a5fc1706df4e80f3db0459bfc831b339838af4a783f7c0eabc","outputIndex":0,"sequenceNumber":4294967295,"script":"473044022033faff638da5f3ca739920cab48f7dd8c0c536aae9c8b841bedac8e18ec7805202201a23304ec221732eb3a1903de3dc226ce57d090ad24a018fc7cbbc06d849cef5012103fdf4907810a9f5d9462a1ae09feee5ab205d32798b0ffcc379442021f84c5bbf","scriptString":"71 0x3044022033faff638da5f3ca739920cab48f7dd8c0c536aae9c8b841bedac8e18ec7805202201a23304ec221732eb3a1903de3dc226ce57d090ad24a018fc7cbbc06d849cef501 33 0x03fdf4907810a9f5d9462a1ae09feee5ab205d32798b0ffcc379442021f84c5bbf","output":{"satoshis":380000000,"script":"76a9148d4d508f5bf2c28b20a3863405f05d3cd374b04588ac"}}],"outputs":[{"satoshis":1000000,"script":"76a914e6e8b8e5f5683bc0e2203e89346fde8587d5593e88ac"},{"satoshis":378900000,"script":"76a9148d4d508f5bf2c28b20a3863405f05d3cd374b04588ac"}],"nLockTime":0,"changeScript":"OP_DUP OP_HASH160 20 0x8d4d508f5bf2c28b20a3863405f05d3cd374b045 OP_EQUALVERIFY OP_CHECKSIG","changeIndex":1,"fee":100000}`

I do n’t know what went wrong

**Comment by HebeBlock** [comment]
@SwenVanZanten HI, need your help

**Comment by justinvforvendetta** [comment]
i mean, its basically telling you the the inputs are newer than the tx time (epoch time)

are you trying to send unconfirmed coins? newly mined? newly received?

**Comment by justinvforvendetta** [comment]
are you trying to send unconfirmed coins? newly mined? newly received?

**Comment by HebeBlock** [comment]
https://xvginsight.guarda.co/#/XVG/mainnet/tx/ed1626de0d42c5a5fc1706df4e80f3db0459bfc831b339838af4a783f7c0eabc

He's confirmed, and 1875 configurations

**Comment by justinvforvendetta** [comment]
are you creating the tx on a vm?

**Comment by HebeBlock** [comment]
nodejs:
let tx = new bitcoreXvg.Transaction()
    .fee(0.1 * 1000000)
    .from([{
            "address": "DJ2ESE1oBt3dHrhrmPc5CD9v8JGRyh7YHd",
            "txid": "ed1626de0d42c5a5fc1706df4e80f3db0459bfc831b339838af4a783f7c0eabc",
            "vout": 0,
            "scriptPubKey": "76a9148d4d508f5bf2c28b20a3863405f05d3cd374b04588ac",
            "amount": 3.8,
            "satoshis": 380000000,
            "height": 4055233,
            "confirmations": 1
        }]
    )
    .to('DSC2kCsRKmZrQwckjV5ZJHNxsUHAr4aoTU', parseInt(1 * 1000000))
    .change(address)
    .sign(privateKey);

**Comment by justinvforvendetta** [comment]
you didnt include the time?

**Comment by justinvforvendetta** [comment]
(also xvg has 6 decimals to the right, 1 xvg is 1.000000, not 1.00000000)

**Comment by HebeBlock** [comment]
How do I add time?
Decimal should not affect, mainly time

**Comment by justinvforvendetta** [comment]
add epoch timestamp and you should be good to go.

**Comment by HebeBlock** [comment]
But i don't know how to add

**Comment by justinvforvendetta** [comment]
add nTime

**Comment by HebeBlock** [comment]
let tx = new bitcore.Transaction()
    .fee(0.1 * 1000000)
    .from([{
            "address": "DJ2ESE1oBt3dHrhrmPc5CD9v8JGRyh7YHd",
            "txid": "ed1626de0d42c5a5fc1706df4e80f3db0459bfc831b339838af4a783f7c0eabc",
            "vout": 1,
            "scriptPubKey": "76a9148d4d508f5bf2c28b20a3863405f05d3cd374b04588ac",
            "amount": 3.8,
            "satoshis": 380000000,
            "height": 4055233,
            "confirmations": 1,
            "nTime": 1589536675
        }]
    )
    .to('DSC2kCsRKmZrQwckjV5ZJHNxsUHAr4aoTU', parseInt(1 * 1000000))
    .change(address)
    .sign(privateKey);

such?

**Comment by SwenVanZanten** [comment]
Hi instead of “ntime” it would be “timestamp”.

Also I don’t think you’re using the  Transaction.prototype.from function correctly. Not sure tho.

In the Transaction.prototype.toBufferWriter you can see exactly how the hex is created.

**Comment by HebeBlock** [comment]
He succeeded. . .

**Comment by lukas-ss** [comment]
If someone gets the same error, then here's what to do:

```
const bitcore = require("bitcore-lib-xvg");

const tx = new bitcore.Transaction().from(outputs).to(to, amount).fee(fee).change(changeAddress);
const txJson = tx.toJSON();

txJson.timestamp = (Date.now() / 1000) | 0;
delete txJson.hash;

const serializedTx = new bitcore.Transaction().fromObject(txJson).sign(privateKey).serialize();
```
