### ISSUE TITLE
ERROR: Data still available after parsing

### ISSUE THREAD

**Issue by atomlab** [vergecurrency/bitcore#9]
```
git clone https://github.com/vergecurrency/bitcore
cd bitcore
cp .env.example .env
# edit .env
# edit bitcore-docker.config.json
docker-compose up
```

Start failed when connecting to verge node

```
bitcore-node_1            | info: Connected to peer 10.0.3.209 chain=XVG, network=mainnet
bitcore-node_1            | /usr/src/app/packages/bitcore-p2p/lib/messages/utils.js:20
bitcore-node_1            |       throw new Error('Data still available after parsing');
bitcore-node_1            |       ^
bitcore-node_1            |
bitcore-node_1            | Error: Data still available after parsing
bitcore-node_1            |     at Object.checkFinished (/usr/src/app/packages/bitcore-p2p/lib/messages/utils.js:20:13)
bitcore-node_1            |     at AddrMessage.setPayload (/usr/src/app/packages/bitcore-p2p/lib/messages/commands/addr.js:48:9)
bitcore-node_1            |     at Function.exported.commands.(anonymous function).fromBuffer (/usr/src/app/packages/bitcore-p2p/lib/messages/builder.js:78:15)
bitcore-node_1            |     at Messages._buildFromBuffer (/usr/src/app/packages/bitcore-p2p/lib/messages/index.js:103:41)
bitcore-node_1            |     at Messages.parseBuffer (/usr/src/app/packages/bitcore-p2p/lib/messages/index.js:74:15)
bitcore-node_1            |     at Peer._readMessage (/usr/src/app/packages/bitcore-p2p/lib/peer.js:220:31)
bitcore-node_1            |     at Peer._readMessage (/usr/src/app/packages/bitcore-p2p/lib/peer.js:223:10)
bitcore-node_1            |     at Peer._readMessage (/usr/src/app/packages/bitcore-p2p/lib/peer.js:223:10)
bitcore-node_1            |     at Peer._readMessage (/usr/src/app/packages/bitcore-p2p/lib/peer.js:223:10)
bitcore-node_1            |     at Peer._readMessage (/usr/src/app/packages/bitcore-p2p/lib/peer.js:223:10)
bitcore-node_1            |     at Peer._readMessage (/usr/src/app/packages/bitcore-p2p/lib/peer.js:223:10)
bitcore-node_1            |     at Socket.<anonymous> (/usr/src/app/packages/bitcore-p2p/lib/peer.js:168:10)
bitcore-node_1            |     at emitOne (events.js:116:13)
bitcore-node_1            |     at Socket.emit (events.js:211:7)
bitcore-node_1            |     at addChunk (_stream_readable.js:263:12)
bitcore-node_1            |     at readableAddChunk (_stream_readable.js:250:11)
bitcore-node_1            |     at Socket.Readable.push (_stream_readable.js:208:10)
bitcore-node_1            |     at TCP.onread (net.js:597:20)
bitcore-node_1            | npm ERR! code ELIFECYCLE
bitcore-node_1            | npm ERR! errno 1
bitcore-node_1            | npm ERR! bitcore-node@8.1.1 start: `npm run tsc && node build/src/server.js`
bitcore-node_1            | npm ERR! Exit status 1
bitcore-node_1            | npm ERR!
bitcore-node_1            | npm ERR! Failed at the bitcore-node@8.1.1 start script.
bitcore-node_1            | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
bitcore-node_1            | npm ERR! A complete log of this run can be found in:
bitcore-node_1            | npm ERR!     /root/.npm/_logs/2020-04-10T16_22_12_424Z-debug.log
bitcore-node_1            | npm ERR! code ELIFECYCLE
bitcore-node_1            | npm ERR! errno 1
bitcore-node_1            | npm ERR! @8.1.0 node: `cd packages/bitcore-node && npm start`
bitcore-node_1            | npm ERR! Exit status 1
bitcore-node_1            | npm ERR!
bitcore-node_1            | npm ERR! Failed at the @8.1.0 node script.
bitcore-node_1            | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
bitcore-node_1            |
bitcore-node_1            | npm ERR! A complete log of this run can be found in:
bitcore-node_1            | npm ERR!     /root/.npm/_logs/2020-04-10T16_22_12_443Z-debug.log
```

**Comment by justinvforvendetta** [comment]
is this your first time running this @atomlab

**Comment by marpme** [comment]
Seems like we have to adjust address parsing due to the latest changes on 6.0.2
We had to adjust torv3 addresses and thus we always allocate a bigger buffer than usual

**Comment by justinvforvendetta** [comment]
you could use `./verged --without-tor`

**Comment by marpme** [comment]
Nah won't change net communication messages at all, might be really incompatible with 6.0.2

Ref: https://github.com/vergecurrency/verge/blob/949f1083c12985d9db818472ab76d83c7c909fa1/src/netaddress.h#L40

**Comment by SwenVanZanten** [comment]
> Seems like we have to adjust address parsing due to the latest changes on 6.0.2
> We had to adjust torv3 addresses and thus we always allocate a bigger buffer than usual

Thought I already fixed that... [here](https://github.com/vergecurrency/bitcore/commit/1558d77adb13d0249f7f282f13542f60c786f0f7)
@atomlab you have the latest pull?

**Comment by atomlab** [comment]
> is this your first time running this @atomlab

Yes

**Comment by atomlab** [comment]
> you could use `./verged --without-tor`

my current verge config

```
datadir = /opt/verge/storage
daemon = 1
server = 1
rpcuser = rpc
rpcpassword = rpc
rpcport = 20102
port = 21102
txindex = 1
without-tor = 1
rpcworkqueue = 1100
maxmempool = 2000
dbcache = 1000
whitelist = 127.0.0.1
```

**Comment by atomlab** [comment]
It's strange. After couple of days bitcore has synced and continues to work. 

`curl http://127.0.0.1:3000/api/XVG/mainnet/block/tip`
>{"_id":"5e92f335df5facb88db2890d","chain":"XVG","network":"mainnet","hash":"000000000214a81c89c8d7031e7e6bf5bc4767c92968fd29a05bcfdc79513eef","height":20237,"version":4,"size":218,"merkleRoot":"65242ced16075afe63fa9ddb43da519343a6cac59a89eee0c6f9b479b625a45d","time":"2014-10-24T22:38:22.000Z","timeNormalized":"2014-10-24T22:38:22.000Z","nonce":3029873,"bits":470388864,"previousBlockHash":"00000000042180e5a225060387b3a29c807d48c2a3a48d2ef530056c391b885e","nextBlockHash":"000000000112becb3b060c5a7118b3d44e8b45d5a0421a3426959bc88331257a","reward":100000000000,"transactionCount":1,"confirmations":-14681}

>{"_id":"5e92f37edf5facb88db38fd4","chain":"XVG","network":"mainnet","hash":"00000000007c75a08424878027899b1b8c6d28085939e78cfe7ec0821a0644b0","height":22058,"version":4,"size":218,"merkleRoot":"d1c35550bb131612b30ec1159d61b71e2996d316d4e38ef67d297ba086dae023","time":"2014-10-27T10:12:30.000Z","timeNormalized":"2014-10-27T10:12:30.000Z","nonce":2884337671,"bits":469828792,"previousBlockHash":"00000000010c71b36dba2dbd29b0e29c92abe2482daa2722758af73f877b6a25","nextBlockHash":"0000000000bfea0d66b1f973400d70a7fa8f1314983beae12a58cac943ff90c0","reward":100000000000,"transactionCount":1,"confirmations":-16502}

**Comment by atomlab** [comment]
1. I have updated verge node from 6.0.0 up to 6.0.2
2. Mongodb data have been wiped
3. Verge node fully synced
4. Verge Bitcore have run from master(a8bc5da2c)

All works! Thank you!
